name: Test Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Test PropReports Export Action
      uses: ./
      with:
        propreports-domain: 'demo.propreports.com'
        propreports-user: 'demo'
        propreports-pass: 'demo'
        commit-exports: 'false'